name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environnement de déploiement'
        required: true
        default: 'develop'
        options:
          - Develop
          - Preproduction
          - Production
  push:
    branches:
      - main
      - exo-1
  pull_request:
    branches:
      - main
      - exo-1

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20, 22]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Generate Unit Test Summary
        run: |
          echo "### Unit Test Results" >> $GITHUB_STEP_SUMMARY
          echo "| Node.js Version | Status   |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------------|----------|" >> $GITHUB_STEP_SUMMARY
          echo "| ${{ matrix.node-version }} | Success ✅ |" >> $GITHUB_STEP_SUMMARY

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: unit-tests 
    if: ${{ github.event.inputs.environment == 'production' }}  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          mkdir ./dist
          npm run build  

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-project
          path: dist/

      - name: Generate Build Summary
        run: |
          echo "### Build Results" >> $GITHUB_STEP_SUMMARY
          echo "| Step          | Status   |" >> $GITHUB_STEP_SUMMARY
          echo "|---------------|----------|" >> $GITHUB_STEP_SUMMARY
          echo "| Dependencies  | Installed ✅ |" >> $GITHUB_STEP_SUMMARY
          echo "| Build         | Success ✅ |" >> $GITHUB_STEP_SUMMARY

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build  
    if: ${{ github.event.inputs.environment == 'production' }}  
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production server..."

      - name: Generate Deployment Summary
        run: |
          echo "### Deployment Results" >> $GITHUB_STEP_SUMMARY
          echo "| Step            | Status   |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------------|----------|" >> $GITHUB_STEP_SUMMARY
          echo "| Deployment      | Completed ✅ |" >> $GITHUB_STEP_SUMMARY
